import React from "react";
import Header from "../Components/Header";
import Footer from "../Components/Footer";
import pdf from "../assets/pdf/MOU_INDCOMBODIA.pdf";

function ObligationPage17() {
  const styles = {
    accordionHeader: {
      background: "#ffc107",
      color: "#0a2c5f",
      padding: "15px 20px",
      fontSize: "18px",
      fontWeight: "bold",
      cursor: "pointer",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderRadius: "7px",
    },
  };
  return (
    <>
      <Header />
      <section className="landmark">
        <div className="container my-lg-4 mb-3 fs-5 ">
          <div className="row m-1">
            <div className="col-12  px-lg-4">
              <h4
                className="fw-bold mt-3 bluetxt yellowclr "
                style={styles.accordionHeader}
              >
                MoU between India and USA to access tip line reports on Missing
                and Exploited Children
              </h4>
              <div className="overflow-x-auto aboutpara">
                <table className="min-w-full divide-y divide-gray-200 about-para">
                  <tbody className="bg-white divide-y divide-gray-100">
                    <tr>
                      <td className="">Signatories:</td>
                      <td className="px-3">
                        National Crime Record Bureau (NCRB), India; National
                        Centre for Missing and Exploited Children (NCMEC),
                        United States of America
                      </td>
                    </tr>
                    <tr>
                      <td className="">Objective:</td>
                      <td className="px-3">
                        Outlining standards for the NCRB India to connect to
                        NCMEC’s internal virtual private network for the limited
                        purpose of downloading CyberTipline reports generated by
                        NCMEC’s Exploited Children Division
                      </td>
                    </tr>

                    <tr>
                      <td className="">Signed on:</td>
                      <td className="px-3">26 April 2019</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div className="main mt-4 about-para">
                <h4 className="fw-bold">Important aspects:</h4>
                <ul className="aboutpara">
                  <li>
                    The MoU shall stay in effect subject to NCMEC’s right to
                    suspension NCRB India’s access to the VPN service through
                    which access to the reports is possible.
                  </li>
                  <li>
                    NCRB India only uses the VPN Service to download
                    CyberTipline Reports.
                  </li>
                  <li>
                    Every authorized user’s contact information is provided to
                    NCMEC, following which training is provided by NCMEC for an
                    introductory online demonstration.
                  </li>
                  <li>
                    A cyberline notation consisting of the subject of a request
                    from another law enforcement agency within the country, NCRD
                    India provides the Report to the requesting law agency and
                    NCMEC with the date when the Report was forwarded to the
                    requesting agency.
                  </li>
                  <li>
                    There are provisions for NCRB India to provide feedback to
                    NCMEC with regards to status or usefulness.
                  </li>
                  <li>
                    NCRB India uses the highest industry standards related to
                    the protection of user names and passwords used to access
                    the VPN Service, including virus protection software,
                    personal firewalls etc. NCRB India shall also access the
                    Reports on a standalone computer, maintain an account with
                    an ISP, and maintain compatible equipment necessary to
                    connect to the VPN Service.
                  </li>
                  <li>
                    NCRB shall administer all precaution with respect to
                    sensitive content (direct downloading and investigating
                    associated leads).
                  </li>
                  <li>
                    All information technology is considered legitimate property
                    of NCMEC and ownership lies with NCMEC.
                  </li>
                  <li>
                    NCRB India has no reasonable expectation of privacy in the
                    information transmitted to NCMEC.
                  </li>
                  <li>
                    Some information may be confidential and NCRB India agrees
                    to hold all such Confidential Information in strict
                    confidence.
                  </li>
                  <li>
                    NCMEC expressly disclaims warranties of merchantability with
                    relation to the VPN Service (it is provided “as is”) to the
                    fullest extent permitted by law.
                  </li>
                  <li>
                    NCRB has indemnified NCMEC and its employees from any
                    alleged or actual breach by NCRB India of its obligations
                    under the policy.
                  </li>
                </ul>
              </div>

              <div className="main mt-4">
                <a
                  className="aboutpara link aboutpara fs-6"
                  href={pdf}
                  target  ="_blank"
                >
                  Click here to access the full text of the MoU
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}

export default ObligationPage17;
